{% set name = "servir-aces" %}
{% set version = "0.0.19" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/servir_aces-{{ version }}.tar.gz
  sha256: 1f89e5eb3e5bfad9bcf0b26898f1f65926ac222bf6942717ef0e4bfcde08070b

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}
    - numpy
    - tensorflow >=2.9.3,<=2.15.0
    - earthengine-api
    - python-dotenv >=1.0.0
    - matplotlib-base

test:
  imports:
    - aces
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: "https://github.com/SERVIR/servir-aces"
  summary: Agricultural Classification and Estimation Service (ACES)
  license: GPL-3.0-only
  license_file: LICENSE
  doc_url: "https://servir.github.io/servir-aces/"
  dev_url: "https://github.com/SERVIR/servir-aces"

extra:
  recipe-maintainers:
    - biplovbhandari
